### ISSUE TITLE
DRL Lights

### ISSUE THREAD

**Issue by zarboz** [kmalinich/node-bmw-client#25]
```
function drl_lights() {
	if  (config.lights.drl !== true) return;
		if (config.lights.drl == true){
		switch (status.vehicle.ignition) {
			case 'off' : drl_power_state = false; break;
			default    : drl_power_state = true;
		}

		switch (drl_power_state) {
			case false : {
				io_encode({});
			break;
			}
			case true : {
				io_encode(config.lights.drl_lights);
			}
		} //break;
	}
}
```

Is this something that could be added to LCM module to enable user selectable DRL via config?

PSS I suck at java

**Comment by kmalinich** [comment]
Yeah, it could be done pretty easily. Pretty much like you laid it out here. As it sits, you can get near that functionality by just enabling the auto lights, since it will run the standing lights whenever the ignition is on automatically.

There are some physical wiring changes you can make to a E38/E39/E53 LCM you can do that have some additional benefits too, like allowing more functional flash-to-pass when you have bi-xenons installed (like I do) - I can detail them in another post

What would you like to to do?

**Comment by zarboz** [comment]
Currently i have  a prefacelift e39 with facelight headlights installed 

Angel eyes wired in with harness from a newer BMW I disabled my DRL in my LCM coding as it just kept my projectors on for DRL's 

my concept was to have a defined DRL section... I should probably put running times / hours or a switch to the LCM to see if the headlights are "on" already 

So essentially

If LCM (headlightson == false)
   run DRL
else
turn DRL off
endif

really crude analogy.
